### ISSUE TITLE
다음 번역 의견 구합니다.

### ISSUE THREAD

**Issue by mhhwang2002** [rubykr/docrails#10]
Association-basics.textile을 구해서 번역을 하고 있는데 다음의 절을 만났습니다. 그런데 내용을 잘 몰라서 그런것 같은데 번역을 해 놓고 봐도 이게 뭔소리인줄을 알길이 없군요.

h6(#belongs_to-class_name). +:class_name+

If the name of the other model cannot be derived from the association name, you can use the +:class_name+ option to supply the model name. For example, if an order belongs to a customer, but the actual name of the model containing customers is +Patron+, you'd set things up this way:

<ruby>
class Order < ActiveRecord::Base
  belongs_to :customer, :class_name => "Patron"
end
</ruby>
만약 관련된 모델의 이름이 파생 될수가 없는 경우에, 당신은 +:class_name+ 옵션을 이용하여 모델 이름을 설정할 수 있다. 예를 들면, 주문이 고객에 속해있으나, 고객들을 가지고 있는 모델의 실제이름이 +Patron+이라면 다음과 같이 설정을 한다. 

이 번역에 화룡정점을 해서 뜻이 더 명확해지게 (의역도 좋습니다.)  도움 주실 의견 기다리겠습니다. 감사합니다.

**Comment by humbroll** [comment]
"만약 모델의 이름이 그 관계와는 다른 이름을 가지고 있다면, 모델명을 지정하기 위하여 +:class_name+ 옵션을 사용할 수 있다. 예를들어 주문이 고객에게 속해 있지만 실제로 고객을 가지고 있는 모델명이 +Patron+이라면 다음과 같이 설정한다. "

(이건 좀 관계 없는 얘기이긴 합니다만, 실제 출판사측에서는 you에 대한 번역을 최대한 빼는 것을 권고합니다. 빼지 않으면 '당신~'이 너무 많이 들어가게 되는 경우가 발생하고 매끄럽지 않게되는 경우도 있습니다^^; 

그나저나 저는 제 범위 맡아놓고 진행을 못하고 있네요 하하하~:) 
이번주에는 꼭~!

**Comment by mhhwang2002** [comment]
어떻게 다른지는 모르겠지만, :-)
humbroll님이 번역해 주신 것을 읽을 때에는 뜻이 전달 되는군요. 님께서 추천하신 방향으로 번역을 수정하겠습니다. 감사합니다.

그리고 저도 왠만하면 "당신"을 넣지 않고 있는데 이 경우에는 넣었나 보군요. 저는 대신에 "우리"라고 번역하고 있어요.
직역하면 이 둘은 반대의 뜻일 수도 있겠지만, 이 문맥에서는 "당신"은 "우리"와도 같은 경우라고 생각이 드는 군요.

즉, 주어가 중요치 않고 모두에게 적용된다는 의미여서, 이 경우 출판사에서 주어 번역을 생략하라고 권하는 이유가 될 듯 하네요.

2011/3/13 humbroll
reply@reply.github.com:

> "만약 모델의 이름이 그 관계와는 다른 이름을 가지고 있다면, 모델명을 지정하기 위하여 +:class_name+ 옵션을 사용할 수 있다. 예를들어 주문이 고객에게 속해 있지만 실제로 고객을 가지고 있는 모델명이 +Patron+이라면 다음과 같이 설정한다. "
> 
> (이건 좀 관계 없는 얘기이긴 합니다만, 실제 출판사측에서는 you에 대한 번역을 최대한 빼는 것을 권고합니다. 빼지 않으면 '당신~'이 너무 많이 들어가게 되는 경우가 발생하고 매끄럽지 않게되는 경우도 있습니다^^;
> 
> 그나저나 저는 제 범위 맡아놓고 진행을 못하고 있네요 하하하~:)
> 이번주에는 꼭~!
> 
> https://github.com/rubykr/docrails/issues/10#comment_867403

**Comment by mhhwang2002** [comment]
humbroll님이 번역해 주신 것을 읽을 때에는 뜻이 전달 되는군요. 
님께서 추천하신 방향으로 번역을 수정하겠습니다. 감사합니다.

그리고 저도 왠만하면 "당신"을 넣지 않고 있는데 이 경우에는 넣었나 보군요. 저는 대신에 "우리"라고 번역하고 있어요.
직역하면 이 둘은 반대의 뜻일 수도 있겠지만, 이 문맥에서는 "당신"은 "우리"와도 같은 경우라고 생각이 드는 군요.

즉, 주어가 중요치 않고 모두에게 적용된다는 의미여서, 이 경우 출판사에서 주어 번역을 생략하라고 권하는 이유가 될 듯 하네요.
