### ISSUE TITLE
구글 번역 지원 도구 소개


### ISSUE THREAD

**Issue by unsouled** [rubykr/docrails#11]
http://translate.google.com/toolkit/

구글에 번역을 지원하는 도구인 "번역사 도구함" 이라는 서비스가 있었군요.
우연한 기회에 알게 됐는데, 현재 작업 중인 문서 하나를 올려서 사용해보고 있는 중입니다.

아직 괜찮은지 어떤지는 잘 감이 오지는 않는데..
원문과 번역 중인 문장을 실시간으로 비교해서 볼 수 있는 기능은 좋은 것 같습니다.
또한 이전에 번역한 비슷한 문구가 있으면 후보로 보여주는 기능인 전체적인 일관성을 맞추는 데에 꽤 도움을  줄 것 같습니다.

용어집 기능도 써보고 싶었지만, csv 로 변환하는 게 귀찮아서, 나중으로 미뤄두었습니다.
번역하시는 다른 분들께 혹시나 도움이 될까하고 올려봅니다.

**Comment by mhhwang2002** [comment]
구글 번역기가 너무나 웃기게 번역을 해서 그걸 유머란 같은데서 봤습니다.
잘 check하시고 사용하세요. 아직 인공지능이라는 것이 사람들 기대에는 못 미치는 듯...

2011/3/14 unsouled
reply@reply.github.com:

**Comment by unsouled** [comment]
링크를 따라가 보셨나요?  
일반인들을 대상으로 한 구글 번역기가 아니라 실제 번역 작업을 하는 번역가들을 위한 도구입니다.
좀 더 사용해 봤는데, 단순히 번역기로 치부하기엔 세세한 기능들이 꽤나 훌륭합니다.
오히려 처음 문서를 업로드할 때 자동 번역하는 기능은 끄고 사용하고 싶을 정도로 자동 번역 기능이 핵심이 아닙니다.

아마 번역 메모리(TM) 라는 기능이 킬러 기능이 될 것 같습니다.
한 문서의 일부를 번역하는 동안 한 두번 TM 100% 검색이 됐었는데, 이게 기계적 번역이 아니고 이미 번역한 내용 중에 유사도가 높은 부분을 검색하는 것이라 TM 100% 검색이 되면 도구가 제안한 번역을 거의 수정없이 쓸 수가 있었습니다.  이 기능은 협업으로 작업해서 TM 을 잘 학습시켜 놓으면 매우 유용할 것 같습니다.

또 번역을 진행한 부분, TM 유사도가 높은 부분 등은 다른 색으로 표시도 가능하고, 진척도도 퍼센티지로 잘 알려줘서 작업이 질리지 않고 진행되는 느낌도 있더군요.

하지만 치명적인 단점은 자동 번역인데.. 코드 부분 까지 번역을 해 버리는 바람에.. 코드를 다시 옮겨줘야 하더군요..
아무튼 저는 좋은 인상을 받아 일단은 계속해서 이 도구를 통해서 작업을 해보렵니다.

**Comment by mhhwang2002** [comment]
오, 그정도라면 저도 한번 테니스를 해 봐야 겠군요.
제쪽의 번역도 상당히 지체되고 있었는데 그 링크가 도움이 될수도 있겠습니다.

PS: 이젠 사람만이 할수 있는 일은 정녕 남지 않았나 봅니다.

2011/3/15 unsouled
reply@reply.github.com:
