### ISSUE TITLE
Active Record Association 를 엑티브 레코드 관계(Association)

### ISSUE THREAD

**Issue by neocoin** [rubykr/docrails#3]
좀 더 직관적인 용어가 있을까?

**Comment by unsouled** [comment]
"관계"는 relation 을 떠올리게 되긴 하네요.
"연관"이라는 단어가 의미상 더 정확한 번역일 거 같은데..
더 직관적인지는 잘 모르겠습니다.

**Comment by mhhwang2002** [comment]
제가 Association-basic 페이지를 번역하고 있는데 Association을 관계로 번역하니깐 영 의미가 안 옵니다. 어떤 분이 지적하셨듯이 연관이 더 나을 것 같아요. 그리고 Active는 그냥 활성으로 현재 번역하고 있어요.

**Comment by neocoin** [comment]
이 주제와 거리가 있지만, 

Active Record
Action Pack
Action View 
Bundler

이들은 각 패키지 명이며 고유 브랜드 입니다. 이를 활성, 행위, 꾸러미 같은걸로 번역하는걸 저는 반대합니다.
