### ISSUE TITLE
eager loading 용어

### ISSUE THREAD

**Issue by neocoin** [rubykr/docrails#5]
<pre>
1. (서술형용사) (…을) 열망[갈망] 하는 (for, after, about); 간절히 (…) 하고 싶어하는(impatient) (to do)
The child is eager to have the plaything. 그 아이는 그 장난감을 몹시 갖고 싶어한다.
2. (서술형용사) (…에) 열성적인 (in, about)
He is very eager in his studies. 그는 공부에 매우 열심이다.
3. (한정형용사) (표정·태도 등이) 열심인
4. (욕망·식욕 등이) 격렬한, 왕성한
5. (고어) (추위가) 심한
L 「날카로운」의 뜻에서
</pre>

from 동아 프라임 in Daum dict ~ [eager - Daum 영어사전](http://engdic.daum.net/dicen/contents.do?query1=E361140)

**Comment by unsouled** [comment]
'선행 로딩' 이라는 표현을 쓰기도 하더군요.  사실 이건 preload 의 의미가 더 강한 것 같긴 합니다.

또 정확한 출처는 기억나지 않지만..
'lazy loading', 'eager loading' 를 각각 '게으른 로딩', '열성적인 로딩' 이라고 표현한 것을 본 적이 있습니다.

**Comment by neocoin** [comment]
게으른 로딩은 병행 표시하면 충분히 전달되고 직관적인거 같습니다. 
열성적인 로딩은 난감하죠. 

말씀중 '선행 로딩'하고 용어 병행 표기가 좋은거 같네요. 그렇게 진행하겠습니다.

**Comment by mhhwang2002** [comment]
그런데 lazy loading과 eager loading은 각각 무슨 뜻입니까? cache를 사용하면 lazy이고 cache를 사용하지 않고 DB를 다시 읽으면 eager loading인가요?

**Comment by neocoin** [comment]
기본적으로 ActiveRecord 의 기본전략은 lazy loading 입니다. 정보를 순회할때 SQL을 실행합니다.

eager loading 은 N+1 문제를 해결하기 위해 lazy loading 중에 지정한걸 모두 가지고 오라고 명령 주는 겁니다. 

http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html

에서 eager loading을 검색해보세요.

**Comment by unsouled** [comment]
용어에 대해서 좀 더 논의할 필요가 있을 것 같습니다.
lazy loading / eager loading 을 게으른 로딩 / 선행 로딩으로 번역을 하면 두 단어 사이에서 오는 대조적이 느낌이 사라지는 것 같습니다.

그래서 eager loading 을 '선행 로딩'으로 번역할 경우, lazy loading 을 '지연 로딩' 이라고 하는 것이 더 자연스러울 것 같고..
lazy loading 을 게으른 로딩이라고 할 경우, eager loading 을 '이른 로딩 / 미리 로딩 / 열성적 로딩' 등 으로 번역하는 것이 자연스러울 것 같습니다.

**Comment by neocoin** [comment]
두개는 대조적인 개념이 아닙니다. 다르게 느껴져야 합니다.

lazy loading 의 반대는 early loading 정도가 되고 객체가 쓰여지기 전에 정보가 적재되는 것을 의미해야하는데, 이 기법은 레일스에서 지양되고 있습니다. 

eager loading을 대체할 한국말 사례는 현재는 없습니다. 개념이 '이른과 미리'와는 다르기 때문에 정확하게는 '열성적 로딩'이 좋을 것 같네요. 이렇게 가겠습니다. mhhwang2002 님의 문서에도 이게 등장하는데 아직 여기까지 번역이 안왔군요. 용어집을 변경해두겠습니다.

**Comment by unsouled** [comment]
mhhwang2002 // 
연관된(Associated) 두 모델이 있을 때,  
어느 한 모델의 객체를 fetch 할 때 연관된 모델의 객체까지 미리 fetch 하는 것을 eager loading 이라고 하고,
연관된 모델의 객체는 실제로 사용이 될 때에 fetch 하는 것을 lazy loading 이라고 합니다.

예를 들어 Post 와 Comment 가 1:N 관계가 있다고 할 때,
Post.find(1) 을 했을 때,  db 에서 post 와 post 와 연관된 comment 모두를 쿼리해서 가져왔다면, eager loading 입니다.  이 때 post.comments 를 호출하면 다시 db 에 쿼리하지 않고 이미 가져온 결과를 이용하게 됩니다.

반면에, find 에선 post 만 가져오고 post.comments 와 같은 메소드가 호출될 때, comment 를 db 에 쿼리해서 가져왔다면, lazy loading 입니다.
